name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install backend dependencies
        working-directory: ./backend
        run: |
          if [ -f package.json ]; then npm install; fi

      - name: Build backend
        working-directory: ./backend
        run: |
          if [ -f package.json ]; then npm run build || echo "No build script"; fi

      - name: Install frontend dependencies
        working-directory: ./ProjeKitap
        run: |
          if [ -f package.json ]; then npm install; fi

      - name: Build frontend
        working-directory: ./ProjeKitap
        run: |
          if [ -f package.json ]; then npm run build || echo "No build script"; fi

      # - name: Run tests (uncomment if you have tests)
      #   working-directory: ./ProjeKitap
      #   run: npm test 